name: AXIS-Adder Pre-Commit Workflow
on: 
  workflow_dispatch:
  pull_request:
    branches: main
jobs:
  AXIS-Adder-Pre-Commit:
    strategy:
      matrix:
        WIDTH: [4, 7, 12]
    runs-on: ubuntu-latest
    container: vshev92/iverilog:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          iverilog src/adder_comb.v \
                   src/adder_axis_cu.v \
                   src/axis_inf_cu.v \
                   src/adder_axis_pipe.v \
                   tests/adder_axis_tb.v \
                   -I tests \
                   -D WIDTH=${{ matrix.WIDTH }} \
                   -o adder_snap
      - name: Simulation
        run: |
          SEED=`rand`
          echo $SEED
          vvp adder_snap +seed=$SEED | tee log.txt
      - name: Check Results
        run: |
          if grep -q PASSED log.txt; then
            exit 0
          else
            exit 1
          fi
